# [MiProyectoDB]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [MiProyectoDB]    Script Date: 26/08/2025 17:17:42 ******/
CREATE DATABASE [MiProyectoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiProyectoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MiProyectoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MiProyectoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MiProyectoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MiProyectoDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiProyectoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MiProyectoDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MiProyectoDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MiProyectoDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MiProyectoDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MiProyectoDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MiProyectoDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MiProyectoDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MiProyectoDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MiProyectoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MiProyectoDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MiProyectoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MiProyectoDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MiProyectoDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MiProyectoDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MiProyectoDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MiProyectoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MiProyectoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MiProyectoDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MiProyectoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MiProyectoDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MiProyectoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MiProyectoDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MiProyectoDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MiProyectoDB] SET  MULTI_USER 
GO
ALTER DATABASE [MiProyectoDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MiProyectoDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MiProyectoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MiProyectoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MiProyectoDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MiProyectoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MiProyectoDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [MiProyectoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Cliente]

In [0]:
USE [MiProyectoDB]
GO

In [0]:
/****** Object:  Table [dbo].[Cliente]    Script Date: 26/08/2025 17:17:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[id_cliente] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[apellido] [varchar](50) NULL,
	[dni_ruc] [varchar](15) NULL,
	[direccion] [varchar](100) NULL,
	[telefono] [varchar](15) NULL,
	[correo] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Empleado]

In [0]:
/****** Object:  Table [dbo].[Empleado]    Script Date: 26/08/2025 17:17:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[id_empleado] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[apellido] [varchar](50) NULL,
	[dni] [char](8) NULL,
	[cargo] [varchar](50) NULL,
	[salario] [decimal](10, 2) NULL,
	[fecha_contratacion] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Empleados]

In [0]:
/****** Object:  Table [dbo].[Empleados]    Script Date: 26/08/2025 17:17:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleados](
	[idempleado] [int] NULL,
	[Nombre] [varchar](20) NULL,
	[Apellido] [varchar](30) NULL,
	[edad] [numeric](2, 0) NULL,
	[telefono] [numeric](10, 0) NULL,
	[direccion] [varchar](100) NULL,
	[fecha_nacimiento] [date] NULL,
	[salario] [decimal](18, 2) NULL,
	[activo] [char](2) NULL
) ON [PRIMARY]
GO

# [dbo].[Producto]

In [0]:
/****** Object:  Table [dbo].[Producto]    Script Date: 26/08/2025 17:17:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[id_producto] [int] NOT NULL,
	[nombre] [varchar](50) NULL,
	[descripcion] [text] NULL,
	[precio] [decimal](10, 2) NULL,
	[stock] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Proveedor]

In [0]:
/****** Object:  Table [dbo].[Proveedor]    Script Date: 26/08/2025 17:17:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Proveedor](
	[id_proveedor] [int] NOT NULL,
	[razon_social] [varchar](100) NULL,
	[ruc] [char](11) NULL,
	[direccion] [varchar](100) NULL,
	[telefono] [varchar](15) NULL,
	[correo] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_proveedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Empleados]

In [0]:
INSERT [dbo].[Empleados] ([idempleado], [Nombre], [Apellido], [edad], [telefono], [direccion], [fecha_nacimiento], [salario], [activo]) VALUES (1, N'jose', N'feliciano', CAST(35 AS Numeric(2, 0)), CAST(1234567890 AS Numeric(10, 0)), N'calle primera no 1', CAST(N'1980-07-03' AS Date), CAST(3000.00 AS Decimal(18, 2)), N'SI')
INSERT [dbo].[Empleados] ([idempleado], [Nombre], [Apellido], [edad], [telefono], [direccion], [fecha_nacimiento], [salario], [activo]) VALUES (2, N'Luis', N'Fernandez', CAST(33 AS Numeric(2, 0)), CAST(1234567891 AS Numeric(10, 0)), N'calle segunda no 2', CAST(N'1980-06-03' AS Date), CAST(4000.00 AS Decimal(18, 2)), N'NO')
GO

# [UQ__Cliente__A56BBF575756690B]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Cliente__A56BBF575756690B]    Script Date: 26/08/2025 17:17:43 ******/
ALTER TABLE [dbo].[Cliente] ADD UNIQUE NONCLUSTERED 
(
	[dni_ruc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [UQ__Empleado__D87608A7766560D3]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Empleado__D87608A7766560D3]    Script Date: 26/08/2025 17:17:43 ******/
ALTER TABLE [dbo].[Empleado] ADD UNIQUE NONCLUSTERED 
(
	[dni] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [UQ__Proveedo__C2B74E61EF510B96]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Proveedo__C2B74E61EF510B96]    Script Date: 26/08/2025 17:17:43 ******/
ALTER TABLE [dbo].[Proveedor] ADD UNIQUE NONCLUSTERED 
(
	[ruc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [MiProyectoDB]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [MiProyectoDB] SET  READ_WRITE 
GO